-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtgCWzlsMeL/MxurO
6DekVenkCi3X5xcNuT5rJRhj/yygCgYIKoZIzj0DAQehRANCAAQKmZyBb7uEiYMd
CgnRLGrV/rtrQq0KGlCAV7+qWMVMsDmvg0TZh0l602CPEW66TjL9l6pFLKb+inrB
XiCz1DUM
-----END PRIVATE KEY-----